name: Lint

on:
  pull_request:
    branches-ignore:
      - "renovate/**"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn lint
      - run: yarn prettier -c
